[package]
name = "binary-search-tree"
version = "0.1.0"
edition = "2018"
author = "Jansen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
